### ISSUE TITLE
pypref.Preference should support Path-like objects

### ISSUE THREAD

**Issue by jtmoon79** [bachiraoun/pypref#5]
`pypref.Preference` arguments should allow `pathlib.Path` objects for either `filename` or `directory`.

Currently, passing a `Path` raises a `TypeError`
```python
>>> import pypref
>>> import pathlib
>>> pypref.Preferences(filename="config", directory=pathlib.Path("C:\Temp"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user1\project1\.venv-3.9.7\lib\site-packages\pypref\Preferences.py", line 164, in __init__
    self.__set_directory(directory=directory)
  File "C:\Users\user1\project1\.venv-3.9.7\lib\site-packages\pypref\Preferences.py", line 203, in __set_directory
    self.__directory = _normalize_path(directory)#directory
  File "C:\Users\user1\project1\.venv-3.9.7\lib\site-packages\pypref\Preferences.py", line 100, in _normalize_path
    path = re.sub(r'([\\])\1+', r'\1', path).replace('\\','\\\\')
  File "C:\Python\python.org-3.9.7\Lib\re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

----

Using pypref version 3.1.0.

**Comment by bachiraoun** [comment]
pypref is developed to work on python 2 and 3. I think it's time to patch it so it can consume pathlib objects as well.

the code is now patched to consume pathlib objects. your script should work and you can always for the following 

`pypref.Preferences(filename="config", directory=str(pathlib.Path("C:\Temp").resolve()) )`
